name: noteng
description: "2024 - DJUnicode - NOTENG"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  youtube_player_flutter: ^9.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/img/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

  